apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: roboshop
  region: us-east-1

accessConfig:
  authenticationMode: API_AND_CONFIG_MAP

  accessEntries:
    - principalARN: arn:aws:iam::892577688117:user/devops-trainee
      type: STANDARD
      kubernetesGroups:
        - devops-trainees

    - principalARN: arn:aws:iam::892577688117:user/raheem
      type: STANDARD
      kubernetesGroups:
        - devops-trainees

    - principalARN: arn:aws:iam::892577688117:user/sivakumar
      type: STANDARD
      kubernetesGroups:
        - devops-trainees